export const CHANGE_FORM = 'CHANGE_FORM'
export const SET_AUTH = 'SET_AUTH'
export const SENDING_REQUEST = 'SENDING_REQUEST'
export const LOADING_AUTH = 'LOADING_AUTH'
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'
export const SET_DATA = 'SET_DATA'
